apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-deployment
  annotations:
    link.argocd.argoproj.io/external-link: https://hub.docker.com/repository/docker/matheuscarino/argocd-private-repo/
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: hello-deployment
        image: matheuscarino/argocd-private-repo:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
